### ISSUE TITLE
Problem with ShaarliOS connecting to my Shaarli

### ISSUE THREAD

**Issue by hobbesjaap** [mro/ShaarliOS#25]
I'm trying to get ShaarliOS to work with my self-hosted installation of Shaarli.

I've got mine all set with a proper Let's Encrypt SSL certificate and it's working just fine. Due to the self-hosted nature, it's not running on the expected HTTPS port 443, but on a different port, 39215. (Not the real port number, keeping it vague for security reasons :))

In the URL setup of ShaarliOS I've put:

shaarli.domain.com:39215

I've tried it with/without https:// in front of that.

Before I had SSL setup, I got the error it couldn't find the server. Now it can, but the error code in the app is "Expected status 200, got 400".

Any help/guidance on why that might be? Do I drop the port number somewhere els? When I take it away, it doesn't work (since port 443 is already in use for something else on my server).

Many thanks in advance - the app looks great and I'd love to use it!

**Comment by mro** [comment]
thanks for reporting, I'll look into it tomorrow what happens if there's a port specified.

what App version are you using?

**Comment by mro** [comment]
tl:dr; I guess Apple interferes with the connection and there's nothing I can do about it.

I set up https://demo.0x4c.de:8443/shaarli-v0.41b/ (uid demo pwd demodemodemo) and can open that only in Safari (iOS 13.4). Neither [iCab Mobile](https://apps.apple.com/us/app/icab-mobile-web-browser/id308111628) nor [Firefox](https://apps.apple.com/us/app/firefox-private-safe-browser/id989804926) do.

Can you confirm that there is a non-Apple App that opens the URL above? Which one?

P.S.: On the simulator the log shows

```
2020-03-28 12:35:05.446659+0100 ShaarliOS[1823:36095] Task <3020AA6B-6C56-4595-B329-5DF12EFB2673>.<1> HTTP load failed (error code: -1005 [4:-4])
2020-03-28 12:35:05.446857+0100 ShaarliOS[1823:36316] Task <3020AA6B-6C56-4595-B329-5DF12EFB2673>.<1> finished with error - code: -1005
probed 'http://demo:demodemodemo@demo.0x4c.de:8443/shaarli-v0.41b/' -> (, , The network connection was lost.)
```

**Comment by mro** [comment]
related to #22

**Comment by hobbesjaap** [comment]
That's odd! The URL you've provided works just fine for me in Firefox (iPadOS 13.4).

I've also got a range of apps that use self-hosted services on custom ports (Reeder & DevonThink being two of them). Both run just fine.

In my Shaarli log (once I try logging into Shaarli through the ShaarliOS app and I get locked out), I can see that the connection is being made, but something goes wrong with how the username & password are put into my Shaarli, since Shaarli says the were too many incorrect attempts.

Does that help at all?

**Comment by hobbesjaap** [comment]
And further to your previous question, what version of Shaarli am I using, I'm running the latest release (0.11.1) from the official Shaarli github: https://github.com/shaarli/Shaarli

**Comment by mro** [comment]
the port issue remains in the recent 1.2.1 version. I guess it's a bug when my App follows the server redirect-dance. A fix will prbly. have to wait until the 1.3.

**Comment by hobbesjaap** [comment]
Dear Marcus, thank you for the update. Then I will eagerly await version 1.3. Thank you!

**Comment by mro** [comment]
- the ShaarliOS v1.2.1 settings screen has a display bug never showing the port of the URL – the port will be properly used however (fixed in 51290ff),
- https://demo.0x4c.de:8443/shaarli-v0.41b/ is too old for non-standard ports – the more recent https://demo.0x4c.de:8443/shaarli-v0.10.2/ works fine.

@hobbesjaap could you plz. confirm?

**Comment by hobbesjaap** [comment]
Hi Marcus, unfortunately it's still the same error for me, the 400 when expecting 200 one. I've sent you a private email about this, since I would prefer not to share my server details with the public.

**Comment by mro** [comment]
@hobbesjaap can you enter this backend URL https://demo.0x4c.de:8443/shaarli-v0.10.2/ with uid `demo` and pwd `demodemodemo` in Settings and (ignore that the port isn't displayed)

1. ensure you have the app version 1.2.1 (most recent),
2. post a note from within the app,
3. post a url via share sheet from e.g. Safari,
4. tell me about it here.

Thanks!

**Comment by hobbesjaap** [comment]
Hi Marcus, I just tested with the URL you provided and it works immediately. I have no idea why mine isn't working though...

**Comment by mro** [comment]
Today I'll try to install the most recent php shaarli version on my demo server to test it with port 8443. Stay tuned and thank you for your patience!

**Comment by hobbesjaap** [comment]
I just dropped a second install of shaarli on my server, so I also went with 0.10.2.

I still get the ShaarliOS response **Expected status 200, got 400**

Back to drawing board...

**Comment by hobbesjaap** [comment]
Fixed it!

As soon as I saw that it was working with your demo site, I knew it had to be something specific other than a port number.

In config.json.php I change open_shaarli from false to true. That seems to have done the trick! Thank you so much for everything, I'll keep you posted but that seems to be the solution.

**Comment by hobbesjaap** [comment]
One step closer! I'm now logged in with ShaarliOS and things seem to be going well. But when I post anything to my Shaarli, it seems to post on ShaarliOS, but nothing is actually showing up on my Shaarli. :(

So sorry about this, I keep bringing up issues that might just be my particular setup... but then I have the Firefox plugin on my desktop and that works, so I'm not sure where I should look.

**Comment by mro** [comment]
@hobbesjaap thank you for your patience and kindness.

I shall submit [v1.2.2](../milestone/7) for review later today, seems to post fine with most recent shaarli and custom port (and firefox 🦊) e.g. at https://demo.0x4c.de:8443/shaarli-v0.11.1/.

**Comment by hobbesjaap** [comment]
It’s working!

The only caveat is that I need to keep my Shaarli publicly accessible, as soon as I hide my public links, ShaarliOS can’t connect. But that’s a small matter - I can easily store my bookmarks now from iPhone and iPad. Thank you for all your help with this!

**Comment by mro** [comment]
That's nice to hear and very interesting! I'll have a look at that usecase.

**Comment by mro** [comment]
@hobbesjaap I'd be happy if you [rate the App](https://apps.apple.com/de/app/shaarlios/id1027441388?mt=8&action=write-review).
